### ISSUE TITLE
Path must be a string 

### ISSUE THREAD

**Issue by smartcodder35** [mattlogan/AndroidImageResizer#1]
I am facing this issue when supplying screen for below
Enter smallest desired image size [xxxhdpi, xxhdpi, xhdpi, hdpi, mdpi, ldpi]: mdpi

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at makeDirectories (/Users/usaleem/Desktop/imageResize/AndroidImageResizer.js:41:8)
    at /Users/usaleem/Desktop/imageResize/AndroidImageResizer.js:31:5
    at Interface._onLine (readline.js:208:5)
    at Interface._line (readline.js:549:8)
    at Interface._ttyWrite (readline.js:826:14)
    at ReadStream.onkeypress (readline.js:105:10)
    at emitTwo (events.js:87:13)
    at ReadStream.emit (events.js:172:7)

**Comment by mattlogan** [comment]
Can you paste each prompt and your input here? I'd like to see what you're using for both the largest and smallest size.

Also, feel free to look at the code and submit a fix. There's not a whole lot there.
